# Generated by Django 5.2.1 on 2025-05-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VitalSigns',
        ),
    ]
