# Generated by Django 5.2.1 on 2025-05-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_delete_vitalsigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharged_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mode_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('insurance', 'Insurance')], default='cash', max_length=10),
        ),
    ]
