# Generated by Django 5.2.1 on 2025-05-19 14:00

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_discharged_time_patient_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(default=patients.models.generate_mrn, max_length=50, unique=True, verbose_name='Medical Record Number'),
        ),
    ]
