# Generated by Django 5.2.1 on 2025-05-20 08:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0002_remove_labtestorder_ordered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Que',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Triage', 'Triage'), ('Internal Medicine', 'Internal Medicine'), ('General Surgery', 'General Surgery'), ('Cardiology', 'Cardiology'), ('Gynecology', 'Gynecology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Pharmacy', 'Pharmacy'), ('Emergency', 'Emergency'), ('Ophthalmology', 'Ophthalmology'), ('Dental', 'Dental'), ('Radiology', 'Radiology'), ('Laboratory', 'Laboratory')], max_length=50)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=10)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Transferred', 'Transferred'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Waiting', max_length=20)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='visits.visit')),
            ],
        ),
    ]
