# Generated by Django 5.2.1 on 2025-05-16 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_delete_vitalsigns'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestorder',
            name='ordered_by',
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='estimated_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'Stat (Immediate)')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_lab_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
